Arabic translation
ACINQ/phoenix pull request #169
Opened 2021-07-29 17:38 UTC by EZ0010

The Arabic translation of Phoenix Wallet, I tried to make it as clear as possible.

I invited some people on Twitter to review this translation and fix what is wrong. [tweet link](https://twitter.com/Bitcoin_info_ar/status/1420780148811575296)

2021-07-29 21:57 UTC, Jean-Gray commented on app/src/main/res/values-ar/strings.xml
> + <p> أصبح بإمكان Phoenix الآن تلقي المدفوعات حتى إذا لم يتم تشغيل التطبيق. </p>
. الآن تلقي المدفوعات حتى إذا لم يتم تشغيل التطبيق Phoenix أصبح بإمكان

2021-07-30 03:23 UTC, Jean-Gray requested changes
Kindly check the suggested changes in the Arabic translation, Good luck
برجاء مراجعة التعديلات المقترحه في الترجمه العربيه ،، بالتوفيق

2021-07-30 03:23 UTC, Jean-Gray commented on app/src/main/res/values-ar/strings.xml
> +<b>تعطيل الخدمة</b>
تم تعطيل الخدمه

2021-07-30 03:23 UTC, Jean-Gray commented on app/src/main/res/values-ar/strings.xml
> + حاول مرة أخرى في وقت لاحق.
كرر المحاوله لاحقاّ

2021-07-30 03:23 UTC, Jean-Gray commented on app/src/main/res/values-ar/strings.xml
> + الرجاء معاودة المحاولة في وقت لاحق.
برجاء تكرار المحاولة لاحقاّ

2021-07-30 09:01 UTC, EZ0010 commented on app/src/main/res/values-ar/strings.xml
> -  <string translatable="false" name="paymentdetails_lnurlpay_success_action_aes_failure">Message from service could not be decrypted.</string>
this string is not translatable as described on the translatable="false"

2021-07-30 09:08 UTC, EZ0010 commented
> Kindly check the suggested changes in the Arabic translation, Good luck
> برجاء مراجعة التعديلات المقترحه في الترجمه العربيه ،، بالتوفيق

Thanks for your review, I edited most of your suggestions except the "Electrum" edit, I tend to not translate names of brands as it doesn't reflect anything when translated.

2021-07-31 15:09 UTC, EZ0010 commented
I built the app and tested it after adding the translation, everything worked well. no RTL issues. the app became RTL without doing anything.

<img width="360" alt="Screen Shot 2021-07-31 at 5 59 01 PM" src="https://user-images.githubusercontent.com/75021359/127744156-c361f8ba-d1f6-4fbc-897c-0066674439db.png">


<img width="360" alt="Screen Shot 2021-07-31 at 5 59 19 PM" src="https://user-images.githubusercontent.com/75021359/127744158-4c99cc5f-35f7-4a25-be17-3afec553d34b.png">


<img width="359" alt="Screen Shot 2021-07-31 at 5 59 38 PM" src="https://user-images.githubusercontent.com/75021359/127744160-196728e0-fae3-40d9-b24f-d7d4ae3f0171.png">

2021-08-09 17:12 UTC, dpad85 commented
Thanks a lot! 

There are some RTL glitches (like the back arrow pointing to the left and the currency picker being misaligned), but it's outside the scope of this PR. I'll review the translation asap.

2021-08-10 07:18 UTC, hima101 commented
if you mean the currency picker in the top of the screen that is because a lot of arabic countries uses Hindu–Arabic numeral system (١٢٣٤٥٦٧٨٩٠) not the Arabic numeral system (1234567890), and these Hindu–Arabic numbers are considered RTL letters that is why they look kinda weird next to "sats", I think the way to solve this is to translating "sats" or any currency into an arabic word. so it will look like (٤٠ ساتوشي) meaning (40 sats)

and btw it is also possible to make the language of the deivce Arabic with Arabic numeric system, just like this:-
<img width="362" alt="Screen Shot 2021-08-10 at 10 14 30 AM" src="https://user-images.githubusercontent.com/88482661/128824269-3cbc1fe8-6509-43f7-afd6-a65900da036b.png">

2021-08-10 09:07 UTC, EZ0010 commented
if you mean the currency picker in the top of the screen that is because a lot of arabic countries uses Hindu–Arabic numeral system (١٢٣٤٥٦٧٨٩٠) not the Arabic numeral system (1234567890), and these Hindu–Arabic numbers are considered RTL letters that is why they look kinda weird next to "sats", I think the way to solve this is by translating "sats" or any currency into an arabic word. so it will look like (٤٠ ساتوشي) meaning (40 sats)

and btw it is also possible to make the language of the deivce Arabic with Arabic numeric system, just like this:-
<img width="362" alt="128824269-3cbc1fe8-6509-43f7-afd6-a65900da036b" src="https://user-images.githubusercontent.com/75021359/128839902-b654ba02-acf9-4fa7-83e7-85e6f93f2dce.png">

2021-08-10 14:02 UTC, dpad85 approved these changes
LGTM

2021-08-10 14:04 UTC, merged