(android) Fix camera keeps running after leaving scanner view (#442)
ACINQ/phoenix pull request #460
Opened 2023-10-27 16:36 UTC by kotasjan

Please test the changes. I am quite confident these changes will work, but I didn't have a chance to build and run it due to hurdles with the project build setup. 😕

2023-10-30 10:07 UTC, dpad85 commented
Thanks, I will look into that ASAP.

2023-11-02 17:48 UTC, dpad85 requested changes
I was able to reproduce issue #442 on a Pixel device with Android 14 (though on a Pixel device with Android 12, the camera does not stay active all the time).

I also tested your changes, and pausing the scanner does fix the issue - however it needs to be applied on other cases (e.g. when copy-pasting). A better solution is to simply use a `DisposableEffect` in the `CameraPermissionsView.onPermissionGranted` callback, instead of a `LaunchedEffect`:

```kotlin
DisposableEffect(key1 = model) {
    if (model is Scan.Model.Ready && initialInput.isNullOrBlank()) scanView?.resume()
    onDispose {
        scanView?.pause()
    }
}
```

If you give me push authorisation on your branch, I can update your PR with that change.

2023-11-02 17:48 UTC, dpad85 commented on phoenix-android/src/main/kotlin/fr/acinq/phoenix/android/payments/ScanDataView.kt
> +            }
This changed can be rolled back if we use a `DisposableEffect`.

2023-11-02 17:48 UTC, dpad85 commented on phoenix-android/src/main/kotlin/fr/acinq/phoenix/android/payments/ScanDataView.kt
> +                }
This change can be rolled back if we use a `DisposableEffect`.

2023-11-02 19:09 UTC, kotasjan commented
> I was able to reproduce issue #442 on a Pixel device with Android 14 (though on a Pixel device with Android 12, the camera does not stay active all the time).
> 
> I also tested your changes, and pausing the scanner does fix the issue - however it needs to be applied on other cases (e.g. when copy-pasting). A better solution is to simply use a `DisposableEffect` in the `CameraPermissionsView.onPermissionGranted` callback, instead of a `LaunchedEffect`:
> 
> ```kotlin
> DisposableEffect(key1 = model) {
>     if (model is Scan.Model.Ready && initialInput.isNullOrBlank()) scanView?.resume()
>     onDispose {
>         scanView?.pause()
>     }
> }
> ```
> 
> If you give me push authorisation on your branch, I can update your PR with that change.

Thank you for the feedback. You are tight with `DisposableEffect` - it is a much cleaner solution. 👍 I have added you to contributors, so you should be able to push your changes now.

2023-11-03 10:16 UTC, dpad85 approved these changes
Thanks again @kotasjan

2023-11-03 10:18 UTC, merged