(ios) Liquidity ads
ACINQ/phoenix pull request #496
Opened 2023-12-22 21:02 UTC by robbiehanson

<img height="450" src="https://github.com/ACINQ/phoenix/assets/304604/5acd8e7e-b9c7-4912-ab2f-724f3bc071e6"/>

<img height="450" src="https://github.com/ACINQ/phoenix/assets/304604/07d13bad-5674-4719-929d-30be168638e7"/>

<br/>

<img height="450" src="https://github.com/ACINQ/phoenix/assets/304604/e0dfa19a-aa19-44db-a1a4-bfeb0bd0ec0f"/>

<img height="450" src="https://github.com/ACINQ/phoenix/assets/304604/1d303707-41d4-4ba9-b89b-e47d6ae7d2ff"/>

<img height="450" src="https://github.com/ACINQ/phoenix/assets/304604/f3f23e22-1182-4707-bc0b-0dd0721bf66c"/>

With a nice little animation:

https://github.com/ACINQ/phoenix/assets/304604/252a0552-4bf3-432e-9009-0c53265a9a3d

2023-12-28 20:54 UTC, robbiehanson commented
<img height="450" src="https://github.com/ACINQ/phoenix/assets/304604/585e974e-b59f-4948-8bd8-865bf4896970"/>
<img height="450" src="https://github.com/ACINQ/phoenix/assets/304604/ed309b3d-bbb7-4991-8e7e-0afe45afdf18"/>

2024-01-02 16:02 UTC, dpad85 requested changes
A few nitpicks:
- we should have a button to request liquidity in the Home screen, similar to the Android app. Without users will not be aware of this new feature. This is temporary, eventually this liquidity button should not be so prominent once we have reworked the onboarding UX.
- buttons navigating to the Request liquidity screen should not be visible if the user does not have any channels

2024-01-02 16:02 UTC, dpad85 commented on phoenix-ios/phoenix-ios/views/configuration/general/liquidity management/LiquidityAdsView.swift
> +
There are several issues with this message:
- quite long (it's scary and people won't read it)
- takes a lot of screen space (on my phone I have to scroll down to reach the interesting part)
- the bucket analogy is kinda advanced and also already in the [FAQ](https://phoenix.acinq.co/faq#what-is-inbound-liquidity).

So the message should be as short as possible (something around "planning ahead to save money later"), with a link to the FAQ for users who want to know more. The FAQ is easier to maintain (shared between iOS and Android), and can be easily updated if we want to add more information.

2024-01-02 21:09 UTC, robbiehanson commented on phoenix-ios/phoenix-ios/views/configuration/general/liquidity management/LiquidityAdsView.swift
> +					params: LiquidityFeeParams(amount: amount, feerate: feePerKw, leaseRate: leaseRate),
Done in 4778664b

2024-01-02 21:45 UTC, robbiehanson commented on phoenix-ios/phoenix-ios/views/configuration/general/liquidity management/LiquidityAdsView.swift
> +					log.error("peer.estimateFeeForInboundLiquidity() == nil")
Done in c7d10c4d

2024-01-02 21:46 UTC, robbiehanson commented on phoenix-ios/phoenix-ios/views/configuration/general/liquidity management/LiquidityAdsView.swift
> +					log.error("peer.requestInboundLiquidity() == nil")
Done in c7d10c4d

2024-01-03 21:59 UTC, robbiehanson commented
New minimal design:

<img height="450" src="https://github.com/ACINQ/phoenix/assets/304604/1da7d364-71d9-440a-838a-dddeafeaab18"/>

Standard "help" button in upper-right corner, displays a help screen:

<img height="450" src="https://github.com/ACINQ/phoenix/assets/304604/7464c07d-30d9-4da3-9623-8bb82880e62f"/>

And a new "add liquidity" button on the home screen (only displayed if user has a channel):

<img height="450" src="https://github.com/ACINQ/phoenix/assets/304604/711c0bae-3954-43c0-b78c-4a7907ce05b8"/>

2024-01-04 16:42 UTC, dpad85 approved these changes
🚀

2024-01-04 16:46 UTC, merged